server:
  port: ${PORT:8080}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: testerherble123
#    password: postgres
    url: jdbc:postgresql://localhost:5432/
#    url: jdbc:postgresql:///postgres
#    url: jdbc:postgresql://localhost:5432/herble
#    hikari:
#        data-source-properties:
#          socketFactory: com.google.cloud.sql.postgres.SocketFactory
#          cloudSqlInstance: herble-test-2:europe-west1:herble-test-3
  jpa:
    hibernate:
      auto_quote_keyword: true
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
      host: smtp.gmail.com
      port: 587
      username: testerherble@gmail.com
      password: tpxooriicpzefuyh
      properties:
          mail:
              smtp:
                auth: true
                starttls:
                    enable: true

management.endpoints.web.exposure.include: prometheus,health,metrics

app:
  firebase-configuration-file: herble-efae7-firebase-adminsdk-r5ptw-491f69e7bc.json
  firebase.android.config.ttl: 2




